select setval('app.activities_id_seq', coalesce(max(id), 1)) from app.activity;
select setval('app.adhoc_queries_id_seq', coalesce(max(id), 1)) from app.adhoc_queries;
select setval('app.appbunos_id_seq', coalesce(max(id), 1)) from app.appbunos;
select setval('app.appdata_id_seq', coalesce(max(id), 1)) from app.appdata;
select setval('app.attachments_id_seq', coalesce(max(id), 1)) from app.attachments;
select setval('app.bunos_id_seq', coalesce(max(id), 1)) from app.bunos;
select setval('app.dashboardreport_id_seq', coalesce(max(id), 1)) from app.dashboardreports;
select setval('app.groups_id_seq', coalesce(max(id), 1)) from app.groups;
select setval('app.issueattachments_id_seq', coalesce(max(id), 1)) from app.issueattachments;
select setval('app.issues_id_seq', coalesce(max(id), 1)) from app.issues;
select setval('app.issuetypes_id_seq', coalesce(max(id), 1)) from app.issuetypes;
select setval('app.mastertypes_id_seq', coalesce(max(id), 1)) from app.masterdata;
select setval('app.priority_id_seq', coalesce(max(id), 1)) from app.priority;
select setval('app.reporttemplates_id_seq', coalesce(max(id), 1)) from app.reporttemplates;
select setval('app.resourcetypes_id_seq', coalesce(max(id), 1)) from app.resourcetypes;
select setval('app.roleassignments_id_seq', coalesce(max(id), 1)) from app.roleassignments;
select setval('app.rolepermissions_id_seq', coalesce(max(id), 1)) from app.rolerestrictions;
select setval('app.roles_id_seq', coalesce(max(id), 1)) from app.roles;
select setval('app.status_id_seq',coalesce(max(id), 1)) from app.status;
select setval('app.support_id_seq', coalesce(max(id), 1)) from app.support;
select setval('app.userattachments_id_seq', coalesce(max(id), 1)) from app.userattachments;
select setval('app.usergroups_id_seq', coalesce(max(id), 1)) from app.usergroups;
select setval('app.workflow_actions_id_seq', coalesce(max(id), 1)) from app.workflow_actions;
select setval('app.workflow_states_id_seq', coalesce(max(id), 1)) from app.workflow_states;
select setval('app.workflow_statetransitions_id_seq', coalesce(max(id), 1)) from app.workflow_statetransitions;
select setval('app.workflow_actionresponse_id_seq', coalesce (max(id), 1)) from app.workflow_status;
